### ISSUE TITLE
force SSL (add example to .htaccess)

### ISSUE THREAD

**Issue by DanielRuf** [rocklegend-org/website#11]
The login still does not use https by default. As the current website currently uses a valid LE cert, it should not be a problem.

```
<IfModule mod_rewrite.c>
   RewriteEngine On
   RewriteCond %{HTTPS} !=on
   RewriteRule ^(.*)$ https://%{HTTP_HOST}/$1 [R=301,L]
</IfModule>
```

See more specific examples starting at https://github.com/h5bp/server-configs-apache/blob/master/dist/.htaccess#L346

HSTS should be used if possible https://github.com/h5bp/server-configs-apache/blob/master/dist/.htaccess#L563

PS:
https://www.ssllabs.com/ssltest/analyze.html?d=rocklegend.org
https://securityheaders.io/?q=https%3A%2F%2Frocklegend.org%2F

**Comment by flipace** [comment]
Done.
