### ISSUE TITLE
can't register on website

### ISSUE THREAD

**Issue by comptuzus** [rocklegend-org/website#17]
When I try to register I got a message like:

> Whoops, looks like something went wrong.

**Comment by DanielRuf** [comment]
See https://github.com/rocklegend-org/website/issues/16

Also it is opensource, any help is welcome.

Not sure why mentioned me, I'm not one of the owners or maintainers.

**Comment by DanielRuf** [comment]
https://github.com/rocklegend-org/website/blob/master/app/Http/Controllers/AuthController.php

**Comment by flipace** [comment]
@alexstoick @comptuzus i fixed the issue which caused the form registration not to work -> you should be able to register normally now.

**Comment by comptuzus** [comment]
@flipace thx !
