### ISSUE TITLE
leaked details on website

### ISSUE THREAD

**Issue by DanielRuf** [rocklegend-org/website#3]
@flipace Currently the debug output reveals critical information. I hope these are not really the credentials for the database and email. Please follow me on Twitter so I can DM you in future cases.

PS: Seems these are really the credentials for the database and so on, never use the same password, username and database name.

Oops: https://github.com/rocklegend-org/website/blob/ef17b1d1e3b09d651ab35e686f8594dac8a55459/config/database.php =(

**Comment by flipace** [comment]
hi @DanielRuf the 

```php
 'database'  => env('DB_DATABASE', 'rocklegend-local'),
 'username'  => env('DB_USERNAME', 'rocklegend'),
 'password'  => env('DB_PASSWORD', 'rocklegend'),
```

the env() command in here uses configuration from a .env file (which is not in the repository), the values rocklegend/rocklegend are "defaults" if that env doesnt exist

**Comment by DanielRuf** [comment]
Well, I can still access your database with these credentials, please read the messages on Facebook.

**Comment by DanielRuf** [comment]
Should we still use the development environment variable? https://github.com/rocklegend-org/website/blob/master/public/.htaccess#L1
